[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "telegram-bot"
version = "1.0.0"
description = "Telegram Book Bot"

[tool.poetry.dependencies]
python = "^3.12"
python-telegram-bot = "13.15"

[tool.poetry.dev-dependencies]
